### PR TITLE
feat: Allow posting multiple images using meda_ids

### PR DESCRIPTION
**Pull request by faisalsayed10**
If the user provides any extra media_ids, we can take it and simply append it (with a comma) to our existing `mediaIds` string.

### CODE REVIEW

**Comment by faisalsayed10** [comment]
fixes #10

**Comment by faisalsayed10** [comment]
@adblanc any updates?

**Comment by A-BMT02** [comment]
@faisalsayed10 @adblanc Was this fixed ? 
Can we post multiple images now ?

**Comment by tchret** [comment]
@adblanc do you mind merging that?

**Pull request merged**
